# Slack
# Copyright 2023-present NAVER Corp.
# CC BY-NC-SA 4.0

inner:
  name: core.losses.AugCE
  reg: 0.0005
  model:
      name: TrivialAugment.networks.wideresnet.WideResNet
      depth: 28
      widen_factor: 10
      dropout_rate: 0.0
      num_classes: 100
outer:
  name: core.losses.AugCE
  model:
      name: core.slack.SLACK
      augmentations:
          name: core.augmentations_torch.AugmentationsOptUMirror
          augment_dict:
      b_size: 8
      n_op: 3
      mu_prior: 0.75
      m_opt: True
      dmu: 
        high:
      Dmu: core.magnitude_distributions.SmoothedUniform
