# Slack
# Copyright 2023-present NAVER Corp.
# CC BY-NC-SA 4.0

load_main_model: true
model:
  type: resnet18
aug: SLACK
dataset: imagenet100
slack: $ROOT/configs/loss/imagenet100.yaml
cutout: -1
batch: 256
gpus: 1
epoch: 270
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: False
  decay: 0.001
