# Slack
# Copyright 2023-present NAVER Corp.
# CC BY-NC-SA 4.0

load_main_model: true
model:
  type: resnet18
aug: randaugment
dataset: imagenet100
randaug:
  N: 0
  M: 0    # from appendix
  weights: [0.0,1.0]
cutout: -1
batch: 256
gpus: 1
augmentation_search_space: wide_standard
epoch: 270
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
